2020-12-23 17:41:04,674 INFO    MainThread:1616 [wandb_setup.py:_flush():70] setting env: {}
2020-12-23 17:41:04,674 INFO    MainThread:1616 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2020-12-23 17:41:04,674 INFO    MainThread:1616 [wandb_setup.py:_flush():70] setting login settings: {}
2020-12-23 17:41:04,674 INFO    MainThread:1616 [wandb_init.py:_log_setup():303] Logging user logs to /Users/stephanehatgiskessell/Desktop/RL_research_algs/PPO/wandb/run-20201223_174104-1sgyo64a/logs/debug.log
2020-12-23 17:41:04,674 INFO    MainThread:1616 [wandb_init.py:_log_setup():304] Logging internal logs to /Users/stephanehatgiskessell/Desktop/RL_research_algs/PPO/wandb/run-20201223_174104-1sgyo64a/logs/debug-internal.log
2020-12-23 17:41:06,054 INFO    MainThread:1616 [wandb_run.py:_console_start():1237] atexit reg
2020-12-23 17:41:06,055 INFO    MainThread:1616 [wandb_run.py:_redirect():1104] redirect: SettingsConsole.REDIRECT
2020-12-23 17:41:06,055 INFO    MainThread:1616 [wandb_run.py:_redirect():1107] Redirecting console.
2020-12-23 17:41:06,056 INFO    MainThread:1616 [redirect.py:install():204] install start
2020-12-23 17:41:06,056 INFO    MainThread:1616 [redirect.py:install():219] install stop
2020-12-23 17:41:06,056 INFO    MainThread:1616 [redirect.py:install():204] install start
2020-12-23 17:41:06,056 INFO    MainThread:1616 [redirect.py:install():219] install stop
2020-12-23 17:41:06,056 INFO    MainThread:1616 [wandb_run.py:_redirect():1151] Redirects installed.
2020-12-23 17:41:06,060 INFO    MainThread:1616 [wandb_config.py:__setitem__():135] config set learning_rate = 0.0001 - <bound method Run._config_callback of <wandb.sdk.wandb_run.Run object at 0x7fc764b1b358>>
2020-12-23 17:41:06,060 INFO    MainThread:1616 [wandb_run.py:_config_callback():549] config_cb learning_rate 0.0001 {'_wandb': {'cli_version': '0.10.12', 'python_version': '3.6.12', 'is_jupyter_run': False, 'is_kaggle_kernel': False, 'framework': 'torch'}, 'learning_rate': 0.0001}
2020-12-23 17:41:06,063 INFO    MainThread:1616 [wandb_watch.py:watch():35] Watching
2020-12-23 17:41:06,819 INFO    MainThread:1616 [wandb_run.py:_atexit_cleanup():1207] got exitcode: 1
2020-12-23 17:41:06,821 INFO    MainThread:1616 [wandb_run.py:_restore():1179] restore
2020-12-23 17:41:06,821 INFO    MainThread:1616 [redirect.py:uninstall():223] uninstall start
2020-12-23 17:41:06,821 INFO    MainThread:1616 [redirect.py:_stop():278] _stop: stdout
2020-12-23 17:41:06,822 INFO    MainThread:1616 [redirect.py:_stop():284] _stop closed: stdout
2020-12-23 17:41:06,822 INFO    stdout    :1616 [redirect.py:_pipe_relay():120] relay done saw last write: stdout
2020-12-23 17:41:06,822 INFO    stdout    :1616 [redirect.py:_pipe_relay():136] relay done done: stdout
2020-12-23 17:41:06,822 INFO    MainThread:1616 [redirect.py:_stop():290] _stop joined: stdout
2020-12-23 17:41:06,822 INFO    MainThread:1616 [redirect.py:_stop():292] _stop rd closed: stdout
2020-12-23 17:41:06,822 INFO    MainThread:1616 [redirect.py:uninstall():227] uninstall done
2020-12-23 17:41:06,822 INFO    MainThread:1616 [redirect.py:uninstall():223] uninstall start
2020-12-23 17:41:06,822 INFO    MainThread:1616 [redirect.py:_stop():278] _stop: stderr
2020-12-23 17:41:06,822 INFO    MainThread:1616 [redirect.py:_stop():284] _stop closed: stderr
2020-12-23 17:41:06,822 INFO    stderr    :1616 [redirect.py:_pipe_relay():120] relay done saw last write: stderr
2020-12-23 17:41:06,822 INFO    stderr    :1616 [redirect.py:_pipe_relay():136] relay done done: stderr
2020-12-23 17:41:06,822 INFO    MainThread:1616 [redirect.py:_stop():290] _stop joined: stderr
2020-12-23 17:41:06,822 INFO    MainThread:1616 [redirect.py:_stop():292] _stop rd closed: stderr
2020-12-23 17:41:06,822 INFO    MainThread:1616 [redirect.py:uninstall():227] uninstall done
2020-12-23 17:41:09,127 ERROR   MainThread:1616 [wandb_run.py:_atexit_cleanup():1225] Problem finishing run
Traceback (most recent call last):
  File "/Users/stephanehatgiskessell/opt/anaconda3/envs/devenv/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 1215, in _atexit_cleanup
    self._on_finish()
  File "/Users/stephanehatgiskessell/opt/anaconda3/envs/devenv/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 1342, in _on_finish
    self.history._flush()
  File "/Users/stephanehatgiskessell/opt/anaconda3/envs/devenv/lib/python3.6/site-packages/wandb/sdk/wandb_history.py", line 59, in _flush
    self._callback(row=self._data, step=self._step)
  File "/Users/stephanehatgiskessell/opt/anaconda3/envs/devenv/lib/python3.6/site-packages/wandb/sdk/wandb_run.py", line 598, in _history_callback
    self._backend.interface.publish_history(row, step)
  File "/Users/stephanehatgiskessell/opt/anaconda3/envs/devenv/lib/python3.6/site-packages/wandb/sdk/interface/interface.py", line 177, in publish_history
    item.value_json = json_dumps_safer_history(v)
  File "/Users/stephanehatgiskessell/opt/anaconda3/envs/devenv/lib/python3.6/site-packages/wandb/util.py", line 600, in json_dumps_safer_history
    return json.dumps(obj, cls=WandBHistoryJSONEncoder, **kwargs)
  File "/Users/stephanehatgiskessell/opt/anaconda3/envs/devenv/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Users/stephanehatgiskessell/opt/anaconda3/envs/devenv/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/stephanehatgiskessell/opt/anaconda3/envs/devenv/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/stephanehatgiskessell/opt/anaconda3/envs/devenv/lib/python3.6/site-packages/wandb/util.py", line 564, in default
    obj, compressed = maybe_compress_history(obj)
  File "/Users/stephanehatgiskessell/opt/anaconda3/envs/devenv/lib/python3.6/site-packages/wandb/util.py", line 467, in maybe_compress_history
    return wandb.Histogram(obj, num_bins=32).to_json(), True
  File "/Users/stephanehatgiskessell/opt/anaconda3/envs/devenv/lib/python3.6/site-packages/wandb/data_types.py", line 273, in __init__
    self.histogram, self.bins = np.histogram(sequence, bins=num_bins)
  File "<__array_function__ internals>", line 6, in histogram
  File "/Users/stephanehatgiskessell/opt/anaconda3/envs/devenv/lib/python3.6/site-packages/numpy/lib/histograms.py", line 792, in histogram
    bin_edges, uniform_bins = _get_bin_edges(a, bins, range, weights)
  File "/Users/stephanehatgiskessell/opt/anaconda3/envs/devenv/lib/python3.6/site-packages/numpy/lib/histograms.py", line 426, in _get_bin_edges
    first_edge, last_edge = _get_outer_edges(a, range)
  File "/Users/stephanehatgiskessell/opt/anaconda3/envs/devenv/lib/python3.6/site-packages/numpy/lib/histograms.py", line 324, in _get_outer_edges
    "autodetected range of [{}, {}] is not finite".format(first_edge, last_edge))
ValueError: autodetected range of [nan, nan] is not finite
